#!/bin/bash

if [ "$1" = "p" ]; then
  NAME="Jo-Jee"
  EMAIL="jojee.dev@gmail.com"
elif [ "$1" = "b" ]; then
  NAME="George (박상조)"
  EMAIL="george.park@bunjang.co.kr"
else
  echo "Please provide the Profile p(personal) or b(business)"
  exit 1
fi

if [ -z "$2" ]
then
  echo "Please provide the Git repo as argument"
  exit 1
fi

git clone "git@bitbucket.org:bunjang/$2"

cd $2
git config user.name "$NAME"
git config user.email "$EMAIL"
