#!/bin/bash

if [ "$1" = "bb" ]; then
  NAME="Jo-Jee"
  EMAIL="jojee.dev@gmail.com"
  REPO="git@github.com:bb-exchange/$2"
elif [ "$1" = "bun" ]; then
  NAME="George (박상조)"
  EMAIL="george.park@bunjang.co.kr"
  REPO="git@bitbucket.org:bunjang/$2"
elif [ "$1" = "hs" ]; then
  NAME="Jo-Jee"
  EMAIL="jojee.dev@gmail.com"
  REPO="git@github.com:hengsan/$2"
else
  echo "Please provide the Profile bb/bun/hs"
  exit 1
fi

if [ -z "$2" ]
then
  echo "Please provide the Git repo as argument"
  exit 1
fi

git clone "$REPO"

cd $2
git config user.name "$NAME"
git config user.email "$EMAIL"
