#!/bin/bash

# PATH 추가
grep -qxF 'export PATH="'$(pwd)':$PATH"' ~/.zshrc || echo -e '\nexport PATH="'$(pwd)':$PATH"\n' >> ~/.zshrc
echo 'PATH added'

PROFILES_DIR="$(pwd)/profiles/*"

grep -qxF "for f in $PROFILES_DIR; do source \$f; done" ~/.zshrc || echo -e "\nfor f in $PROFILES_DIR; do source \$f; done" >> ~/.zshrc

# # kubectl aliases 추가
# grep -qxF "[ -f $(pwd)/.kubectl_aliases ] && source $(pwd)/.kubectl_aliases" ~/.zshrc || echo -e "\n[ -f $(pwd)/.kubectl_aliases ] && source $(pwd)/.kubectl_aliases" >> ~/.zshrc
# echo 'kubectl aliases added'

# # terraform aliases 추가
# grep -qxF "[ -f $(pwd)/.tf_aliases ] && source $(pwd)/.tf_aliases" ~/.zshrc || echo -e "[ -f $(pwd)/.tf_aliases ] && source $(pwd)/.tf_aliases" >> ~/.zshrc
# echo 'terraform aliases added'

# # jenv 추가
# grep -qxF "[ -f $(pwd)/.jenv ] && source $(pwd)/.jenv" ~/.zshrc || echo -e "[ -f $(pwd)/.jenv ] && source $(pwd)/.jenv" >> ~/.zshrc
# echo 'terraform aliases added'
